// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sutnggvyjstgykoyvgqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1dG5nZ3Z5anN0Z3lrb3l2Z3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NjQ0ODUsImV4cCI6MjA4NDE0MDQ4NX0.ngTqHy-cxbQ6iNIBF3AGMN2Im2nEUS046W78iMq8RZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});